stages:
  - test

test:
  stage: test
  image: mcr.microsoft.com/playwright/java:v1.52.0-noble
  parallel:
    matrix:
      - BROWSER: ["chromium", "firefox", "webkit"]
  script:
    - echo "Running Maven tests on $BROWSER"
    - mvn -B -ntp -Dbrowser=$BROWSER -Dheadless=true test
    - mvn -B -ntp surefire-report:report-only
  artifacts:
    when: always
    paths:
      - target/surefire-reports/*.xml
      - target/reports/surefire.html
    expire_in: 7 days