name: CI Pipeline

on:
  workflow_dispatch: # <-- Allow manual triggering
  push:
    branches:
      - multibrowser

jobs:
  test:
    # Use a matrix strategy to launch three parallel jobs
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]

    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.52.0-noble
      options: --user 1001

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Maven tests on ${{ matrix.browser }}
        run: mvn -B -ntp test -Dbrowser=${{ matrix.browser }}

      - name: Upload test reports for ${{ matrix.browser }}
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports-${{ matrix.browser }}
          path: |
            target/surefire-reports/*.xml
            target/reports/surefire.html
          retention-days: 7
