name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ multibrowser ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit]

    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.52.0-noble
      options: --user 1001

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Maven tests (ignore failures) on ${{ matrix.browser }}
        id: run-tests
        run: mvn -B -ntp \
          -Dbrowser=${{ matrix.browser }} \
          -Dheadless=true \
          -Dmaven.test.failure.ignore=true \
          surefire-report:report
        # continue-on-error is implicit since test failures are ignored

      - name: Upload JUnit XML + HTML report for ${{ matrix.browser }}
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports-${{ matrix.browser }}
          path: |
            target/surefire-reports/*.xml
            target/reports/surefire.html
          retention-days: 7

      - name: Check for test failures and fail job
        if: always()
        run: |
          # sum up failures from surefire XML results
          total=$(grep -Eo 'failures="[0-9]+"' target/surefire-reports/*.xml \
                    | cut -d\" -f2 | paste -sd+ - | bc)
          echo "✔️ Total test failures on ${{ matrix.browser }}: $total"
          if [ "$total" -gt 0 ]; then
            echo "::error::Test failures detected – failing this job."
            exit 1
          fi
